# docker run --name postgresql -e POSTGRESQL_USERNAME=api-review -e POSTGRESQL_PASSWORD=review123 -e POSTGRESQL_DATABASE=review -p 5432:5432  bitnami/postgresql:latest

version: '3.8'

services:
  postgresql:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_USERNAME=api-review
      - POSTGRESQL_PASSWORD=review123
      - POSTGRESQL_DATABASE=review
    ports:
      - "5432:5432"
